spring.application.name=ims
spring.profiles.active=dev

spring.datasource.url=jdbc:postgresql://localhost:5432/ims-database
spring.datasource.username=root
spring.datasource.password=password123
spring.jpa.hibernate.ddl-auto=update